In [1]:
import numpy as np
import pandas as pd
from template import *
from collections import Counter
from itertools import combinations

In [ ]:
original=[[1, 2], [1, 3], [1, 4], [1, 5], [2, 3], [2, 4], [2, 5], [3, 4], [3, 5], [4, 5]]

In [1]:
a=[[1],[2],[3],[4],[5]]
b=[[1, 2], [1, 5], [2, 3], [2, 4], [2, 5], [4, 5]]
#b=[[1, 2,3], [1,2,4],[1,2,5], [2, 3,5], [2, 4,5], [2, 5,3], [4, 5,6]]
c=list(set([x for l in b for x in l]))

def aprioriSons(c):
    d=c.copy()
    a=1
    k=1
    for itemset in c:
        for j in range(a,len(d)):
            brothers=True
            for l in range(k):
                if itemset[l]!=d[j][l]:
                    brothers=False
            if brothers:
                
                print(itemset,d[j])
                
        a+=1
    print(d)
    return d
aprioriSons(b)    
#c=[[1,2,5],[2,3,4],[2,3,5]]

[1, 2] [1, 5]
[2, 3] [2, 4]
[2, 3] [2, 5]
[2, 4] [2, 5]
[[1, 2], [1, 5], [2, 3], [2, 4], [2, 5], [4, 5]]


[[1, 2], [1, 5], [2, 3], [2, 4], [2, 5], [4, 5]]

In [54]:
db=readTransactionalDatabase("exampleset.dat")
items=set([x for l in db for x in l])
items=np.array(list(items))
print(items)
Ck=[]
for i,combo in enumerate(combinations(items,2)):
    newCk.append(combo)
    print(combo,i)
newCk=np.array(newCk)    


newCk2=[]

for i in newCk:
    brothers=newCk[np.where(newCk[:,0]==i[0])]
    for j in brothers:
        if j[1]>i[1]:
            newCk2.append(np.unique(np.concatenate((j,i),0)))
newCk2=np.array(newCk2)
print(newCk)
for i in newCk2:
    for combo in combinations(i,2):
        print(combo in newCk)

[1 2 3 4 5]
(1, 2) 0
(1, 3) 1
(1, 4) 2
(1, 5) 3
(2, 3) 4
(2, 4) 5
(2, 5) 6
(3, 4) 7
(3, 5) 8
(4, 5) 9
[[1 2]
 [1 3]
 [1 4]
 [1 5]
 [2 3]
 [2 4]
 [2 5]
 [3 4]
 [3 5]
 [4 5]]
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


In [107]:
db=readTransactionalDatabase("exampleset.dat")

    

[1 2 3 4 5]
[[1 2]
 [1 3]
 [1 4]
 [1 5]
 [2 3]
 [2 4]
 [2 5]
 [3 4]
 [3 5]
 [4 5]] -k: 1
[[1 2 3]
 [1 2 4]
 [1 2 5]
 [1 3 4]
 [1 3 5]
 [1 4 5]
 [2 3 4]
 [2 3 5]
 [2 4 5]
 [3 4 5]] -k: 2
[[1 2 3 4]
 [1 2 3 5]
 [1 2 4 5]
 [1 3 4 5]
 [2 3 4 5]] -k: 3
[[1 2 3 4 5]] -k: 4
[] -k: 5


In [95]:
a=np.array([[1,2,3,4],[1,2,3,5],[1,2,3,6],[1,4,3,5],[2,3,3,2],[2,3,6,5]])
k=3
print(a[np.all(a[:,np.arange(k)]==a[0,0:k],axis=1),:])


[[1 2 3 4]
 [1 2 3 5]
 [1 2 3 6]]


In [133]:
arr = np.arange(5,10)
arr2=np.array([[1,2],[3,4],[5,6],[7,8],[1,1]])
print(arr2)
np.delete(arr2, np.where(arr<8), 0)
print()

[5 6 7 8 9]
[[7 8]
 [1 1]]


In [136]:
for combo in combinations([1,2,4,5],3):
    print(combo)

(1, 2, 4)
(1, 2, 5)
(1, 4, 5)
(2, 4, 5)


In [159]:
arr=np.array([ [1, 2],[1, 4],[1, 5], [2 ,3], [2 ,4], [2 ,5], [3 ,5], [4 ,5]])

b=np.isin(arr, (3,4))
print(np.any(b[:,0]* b[:,1]))

False


In [179]:

arr=np.array([ [1,3],[1,2],[1, 2],[1, 4],[1, 5], [2 ,3], [2 ,4], [2 ,5], [3 ,5], [4 ,5]])
print(arr)
any(np.all(row == [1,2]) for row in arr)

[[1 3]
 [1 2]
 [1 2]
 [1 4]
 [1 5]
 [2 3]
 [2 4]
 [2 5]
 [3 5]
 [4 5]]


True

In [1]:
import collections
from time import time
arr = readTransactionalDatabase("shop.dat")
y=pd.DataFrame(arr,dtype=int).values
tiempo_inicial = time() 
test=[21,  32,  54, 136, 213, 239, 274, 348, 411, 753, 764]
mask = np.isin(y, test)
result=np.sum(mask,1)
finalrest=np.count_nonzero(result== 11)
tiempo_final = time()
print(tiempo_final-tiempo_inicial)
print(mask)
print(result)
finalrest

NameError: name 'readTransactionalDatabase' is not defined

In [12]:
arr = readTransactionalDatabase("original.dat")
y=pd.DataFrame(arr,dtype=int).values
test=[1]
mask = np.isin(y, test)
print((np.where(np.any(mask,1))))

(array([0, 2, 3, 5, 6], dtype=int64),)


In [15]:
def tri_recursion(k):
    if(k>0):
        print(k,"befr")
        result = k+tri_recursion(k-1)
        print(result)
    else:
        result = 0
    return result

print("\n\nRecursion Example Results")
tri_recursion(3)



Recursion Example Results
3 befr
2 befr
1 befr
1
3
6


6

In [18]:
db=readTransactionalDatabase("original.dat")
db=pd.DataFrame(db).values
print(db)
exam=[2,3]
np.count_nonzero(np.sum(np.isin(db,exam),axis=1) ==len(exam))


[[ 1.  2.  4.  5. nan]
 [ 2.  3.  5. nan nan]
 [ 1.  2.  3.  5. nan]
 [ 1.  2.  3.  4.  5.]
 [ 2.  3. nan nan nan]
 [ 1.  3.  5. nan nan]
 [ 1.  2.  3.  5. nan]
 [ 1.  6. nan nan nan]
 [ 7. nan nan nan nan]
 [ 7. nan nan nan nan]
 [ 7. nan nan nan nan]]


5